djp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from django.contrib.auth import views


urlpatterns = [
    url(r'^pedidos/',include('pedidos.urls', namespace='pedidos')),
    url(r'^admin/', include(admin.site.urls)),
    
    #url(r'^pedidos/',include('django.contrib.auth.urls', namespace='pedidos')),
    url(r'^reportes/',include('reportes.urls', namespace='reportes')),
    ]
'''url(r'^accounts/', include('registration.backends.simple.urls')),'''
    


pedidos/urls.py
from django.conf.urls import url
from pedidos import views
#from pedidos.subvi import imprime_documento
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
	url(r'^index/$',views.index,name='index'),
	url(r'^acceso/$',views.acceso,name='acceso'),
	url(r'^asociados/$',views.lista_asociados,name='asociados'),
	url(r'^edita_asociado/(?P<asociadono>[0-9]{1,8})/$',views.edita_asociado,name='edita_asociado'),
	url(r'^crea_asociado/$',views.crea_asociado,name='crea_asociado'),
	url(r'^asociado_proveedor/(?P<asociadono>[0-9]{1,8})/$',views.asociado_proveedor,name='asociado_proveedor'),
	url(r'^asociado_edita_descuento/(?P<proveedorno>[0-9]{1,8})/(?P<asociadono>[0-9]{1,8})/$',views.asociado_edita_descuento,name='asociado_edita_descuento'),
	url(r'^asociado_nuevo_descuento/(?P<asociadono>[0-9]{1,8})/$',views.asociado_nuevo_descuento,name='asociado_nuevo_descuento'),
	url(r'^busca_pedidos/$',views.busca_pedidos,name='busca_pedidos'),
	url(r'^lista_pedidos/$',views.lista_pedidos,name='lista_pedidos'),
	url(r'^crea_pedidos/$',views.crea_pedidos,name='crea_pedidos'),
	url(r'^combo_temporadas/$',views.combo_temporadas,name='combo_temporadas'),
	url(r'^combo_catalogos/$',views.combo_catalogos,name='combo_catalogos'),
	url(r'^combo_estilos/$',views.combo_estilos,name='combo_estilos'),
	url(r'^combo_marcas/$',views.combo_marcas,name='combo_marcas'),
	url(r'^combo_colores/$',views.combo_colores,name='combo_colores'),
	url(r'^combo_tallas/$',views.combo_tallas,name='combo_tallas'),
	url(r'^grabar_pedidos/$',views.grabar_pedidos,name='grabar_pedidos'),
	url(r'^eli_reg_tmp/$',views.eli_reg_tmp,name='eli_reg_tmp'),
	url(r'^procesar_pedido/$',views.procesar_pedido,name='procesar_pedido'),
	url(r'^busca_socio/$',views.busca_socio,name='busca_socio'),
	url(r'^registro_socio/$',views.registro_socio,name='registro_socio'),
	url(r'^llena_combo_sucursal/$',views.llena_combo_sucursal,name='llena_combo_sucursal'),
	url(r'^logout_view/$',views.logout_view,name='logout_view'),
	url(r'^cambiar_password/$',views.cambiar_password,name='cambiar_password'),
	url(r'^reset/password_reset/$',password_reset,
		{'template_name':'pedidos/password_reset_form.html',
		'email_template_name':'pedidos/password_reset_email.html',
		'current_app':'pedidos','post_reset_redirect':'pedidos:password_reset_done'},
		name ='password_reset'),
	url(r'^reset/password_done/$',password_reset_done,
		{'template_name':'pedidos/password_reset_done.html','current_app':'pedidos'},
		name ='password_reset_done'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		password_reset_confirm,
		{'template_name':'pedidos/password_reset_confirm.html',
		'current_app':'pedidos','post_reset_redirect' : 'pedidos:password_reset_complete'},
		name ='password_reset_confirm'),
	url(r'^reset/password_complete/$',password_reset_complete,
		{'template_name':'pedidos/password_reset_complete.html','current_app':'pedidos'},
		name ='password_reset_complete'),
	url(r'^empleados/$',views.empleados,name='empleados'),
	url(r'^entrada_sistema/$',views.entrada_sistema,name='entrada_sistema'),
	url(r'^consulta_menu/$',views.consulta_menu,name='consulta_menu'),
	url(r'^calzadollego_gral/$',views.calzadollego_gral,name='calzadollego_gral'),
	url(r'^con_pedidos_por_socio_status/$',views.con_pedidos_por_socio_status,name='con_pedidos_por_socio_status'),
	url(r'^con_confirmaciones/$',views.con_confirmaciones,name='con_confirmaciones'),
	url(r'^existe_socio/$',views.existe_socio,name='existe_socio'),
	url(r'^picklist_socio/$',views.picklist_socio,name='picklist_socio'),
	url(r'^calzadoquellego_detalle/$',views.calzadoquellego_detalle,name='calzadoquellego_detalle'),
	url(r'^consultacolocaciones/$',views.consultacolocaciones,name='consultacolocaciones'),
	url(r'^consultaventas/$',views.consultaventas,name='consultaventas'),
	url(r'^consultacomisiones/$',views.consultacomisiones,name='consultacomisiones'),
	url(r'^buscapedidosposfecha/$',views.buscapedidosposfecha,name='buscapedidosposfecha'),
	url(r'^pedidosgeneral/$',views.pedidosgeneral,name='pedidosgeneral'),
	# url(r'^pedidosgeneraldetalle/(?P<pedido>[0-9]{1,8})/(?P<productono>[\w\-]+)/(?P<catalogo>[\w\-]+)/(?P<nolinea>[0-9]{1,8})/$',views.pedidosgeneraldetalle,name='pedidosgeneraldetalle'),
	url(r'^pedidosgeneraldetalle/(?P<pedido>[0-9]{1,8})/(?P<productono>.*)/(?P<catalogo>.*)/(?P<nolinea>[0-9]{1,8})/$',views.pedidosgeneraldetalle,name='pedidosgeneraldetalle'),
	#url(r'^cancelarpedidoadvertencia/(?P<pedido>[0-9]{1,8})/(?P<productono>[\w\-]+)/(?P<catalogo>[\w \-]+)/(?P<nolinea>[0-9]{1,8})/$',views.cancelarpedidoadvertencia,name='cancelarpedidoadvertencia'),
	url(r'^cancelarpedidoadvertencia/(?P<pedido>[0-9]{1,8})/(?P<productono>.*)/(?P<catalogo>.*)/(?P<nolinea>[0-9]{1,8})/$',views.cancelarpedidoadvertencia,name='cancelarpedidoadvertencia'),
	#url(r'^ingresa_socio/$',views.ingresa_socio,name='ingresa_socio'),
	url(r'^ingresa_socio/(?P<tipo>[D,P,V]{1})/$',views.ingresa_socio,name='ingresa_socio'),

	url(r'^imprime_ticket/$',views.imprime_ticket,name='imprime_ticket'),
	#url(r'^i_d/$',imprime_documento.i_d,name='i_d'),
	url(r'^colocaciones/$',views.colocaciones,name='colocaciones'),
	url(r'^combo_almacenes/$',views.combo_almacenes,name='combo_almacenes'),
	url(r'^muestra_colocaciones/$',views.muestra_colocaciones,name='muestra_colocaciones'),
	url(r'^procesar_colocaciones/$',views.procesar_colocaciones,name='procesar_colocaciones'),
	url(r'^elegir_almacen_a_cerrar/$',views.elegir_almacen_a_cerrar,name='elegir_almacen_a_cerrar'),
	url(r'^procesar_cierre_pedido/$',views.procesar_cierre_pedido,name='procesar_cierre_pedido'),
	url(r'^pruebaImprime/$',views.pruebaImprime,name='pruebaImprime'),
	url(r'^seleccion_cierre_rpte_cotejo/$',views.seleccion_cierre_rpte_cotejo,name='seleccion_cierre_rpte_cotejo'),
	url(r'^combo_proveedor_rpte_cotejo/$',views.combo_proveedor_rpte_cotejo,name='combo_proveedor_rpte_cotejo'),
	url(r'^seleccion_cierre_recepcion/$',views.seleccion_cierre_recepcion,name='seleccion_cierre_recepcion'),
	url(r'^procesar_recepcion/$',views.procesar_recepcion,name='procesar_recepcion'),
	url(r'^documentos/$',views.documentos,name='documentos'),
	url(r'^muestra_documentos/$',views.muestra_documentos,name='muestra_documentos'),
	url(r'^detalle_documento/(?P<NoDocto>[0-9]{1,8})/$',views.detalle_documento,name='detalle_documento'),
	url(r'^crea_documento/$',views.crea_documento,name='crea_documento'),
	url(r'^consulta_menu/$',views.consulta_menu,name='consulta_menu'),
	url(r'^nueva_venta/$',views.nueva_venta,name='nueva_venta'),
	url(r'^calcula_descuento/$',views.calcula_descuento,name='calcula_descuento'),
	url(r'^procesar_venta/$',views.procesar_venta,name='procesar_venta'),
	url(r'^picklist_estilopagina/$',views.picklist_estilopagina,name='picklist_estilopagina'),
	url(r'^consultadsctos/$',views.consultadsctos,name='consultadsctos'),
	url(r'^consultavtasxproveedor/$',views.consultavtasxproveedor,name='consultavtasxproveedor'),
	url(r'^valida_usr/$',views.valida_usr,name='valida_usr'),
	url(r'^detallevtaxproveedor/(?P<idproveedor>[0-9]{1,8})/(?P<fechainicial>[\w\-]+)/(?P<fechafinal>[\w\-]+)/(?P<sucursalinicial>[0-9]{1,8})/(?P<sucursalfinal>[0-9]{1,8})/$',views.detallevtaxproveedor,name='detallevtaxproveedor'),
	url(r'^detallevtaxsocio/(?P<idproveedor>[0-9]{1,8})/(?P<fechainicial>[\w\-]+)/(?P<fechafinal>[\w\-]+)/(?P<sucursalinicial>[0-9]{1,8})/(?P<sucursalfinal>[0-9]{1,8})/(?P<asociadono>[0-9]{1,8})/$',views.detallevtaxsocio,name='detallevtaxsocio'),
	url(r'^trae_nombre_socio/$',views.trae_nombre_socio,name='trae_nombre_socio'),
	url(r'^modifica_cierre/(?P<id>[0-9]{1,8})/$',views.modifica_cierre,name='modifica_cierre'),
	url(r'^imprime_venta/$',views.imprime_venta,name='imprime_venta'),
	url(r'^imprime_documento/$',views.imprime_documento,name='imprime_documento'),
	url(r'^cancelar_pedido/$',views.cancelar_pedido,name='cancelar_pedido'),
	url(r'^devolucion_socio/$',views.devolucion_socio,name='devolucion_socio'),
	url(r'^procesar_devolucion_socio/$',views.procesar_devolucion_socio,name='procesar_devolucion_socio'),
	url(r'^imprime_credito/$',views.imprime_credito,name='imprime_credito'),
	url(r'^calcula_bono/$',views.calcula_bono,name='calcula_bono'),
	url(r'^detallebonosocio/(?P<idsocio>[0-9]{1,8})/(?P<fechainicial>[\w\-]+)/(?P<fechafinal>[\w\-]+)/$',views.detallebonosocio,name='detallebonosocio'),
	url(r'^vtaneta_socio/$',views.vtaneta_socio,name='vtaneta_socio'),
	url(r'^vtaneta_socio_gral/$',views.vtaneta_socio_gral,name='vtaneta_socio_gral'),
	url(r'^vtaneta_socio_proveedor_gral/(?P<fechainicial>[\w\-]+)/(?P<fechafinal>[\w\-]+)/(?P<asociadoini>[0-9]{1,8})/(?P<asociadofin>[0-9]{1,8})/$',views.vtaneta_socio_proveedor_gral,name='vtaneta_socio_proveedor_gral'),
	url(r'^cancelardocumentoadvertencia/(?P<NoDocto>[0-9]{1,8})/$',views.cancelardocumentoadvertencia,name='cancelardocumentoadvertencia'),	
	url(r'^rptedecreditos/$',views.rptedecreditos,name='rptedecreditos'),
	url(r'^recepcion_dev_prov/$',views.recepcion_dev_prov,name='recepcion_dev_prov'),
	url(r'^procesar_recepcion_devolucion_proveedor/$',views.procesar_recepcion_devolucion_proveedor,name='procesar_recepcion_devolucion_proveedor'),
	url(r'^devolucion_a_proveedor/$',views.devolucion_a_proveedor,name='devolucion_a_proveedor'),
	url(r'^procesar_devolucion_proveedor/$',views.procesar_devolucion_proveedor,name='procesar_devolucion_proveedor'),
	url(r'^filtro_dev_prov/$',views.filtro_dev_prov,name='filtro_dev_prov'),
	url(r'^imprime_hoja_devolucion/$',views.imprime_hoja_devolucion,name='imprime_hoja_devolucion'),
	url(r'^edita_devprov/(?P<id_prov>[0-9]{1,8})/$',views.edita_devprov,name='edita_devprov'),
	url(r'^proveedores/$',views.proveedores,name='proveedores'),

pedidos/templates/pedidos/calzadollego_detalle.html
{% extends 'pedidos/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}

<h1>{{mensaje}}</h1>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-success">
        <div class='panel-heading'><h4 align='center'>Calzado que llego (Detallado)<h4></div>
        <div class='panel-body'>
    
            {{ mensaje }}
            {% if error_message %}<p><strong> {{error_message}}</p>{% endif %}
            <form action="{% url 'pedidos:calzadoquellego_detalle' %}" method="get">
                <div class="form-group">
                    {% csrf_token %}
                    {{ form | crispy }}<br><br>    
                    
                    <input  class="btn btn-default "  type="submit" value="Enviar" />
                    <a class="btn btn-default" href="{% url 'pedidos:consulta_menu' %}" role="button"> Regresar</a>
                </div>
            </form>

        </div>
       

    </div>  
  </div>
  <div class="col-md-4">
    
    
  </div>
  <div class="col-md-4">
    
  </div>
</div>
    










<!-- El siguiente div se utiliza como parte del cuadro de dialogo jquery para elminiar clientes -->

<div id="dialog-1" style="display : none;" title="Advertencia !">Los registros seleccionados serán eliminados de manera definitiva de la base de datos, la acción es irreversible, desea continuar ?</div>





{% endblock content %}

pedidos/templates/pedidos/documento_registrado_exito.html
{% extends 'pedidos/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}


<div class="row">
   
  

  <div class="col-md-12">  

    
    <div class="alert alert-success" role="alert">
        <h3>
        Documento Procesado !<br><br>
        Su documento quedó registrado con el número {% if tipodedocumento == 'Remision' or tipodedocumento == 'Cargo' %} {{ p_num_venta }} {% else %} {{ p_num_credito }} {% endif %}

        </h3><br><br>

        <h4> Puede dar seguimiento de este y todos sus documentos en la sección de consulta de documentos </h4>




    </div>
    
  </div><br><br>
  <div class="col-md-3">
      <form id="imp_venta_form"  role="button" {% if  tipodedocumento == 'Remision' or  tipodedocumento == 'Cargo' %}  action= "{% url 'pedidos:imprime_venta' %}" {% else %} action="{% url 'pedidos:imprime_credito' %}" {% endif %} method="GET"><input id ='idventa' {% if  tipodedocumento == 'Remision' or  tipodedocumento == 'Cargo'  %} name ='p_num_venta' {% else %} name ='p_num_credito' {% endif %} class="glyphicon glyphicon-print" type="submit"  value = "{% if tipodedocumento == 'Remision' or tipodedocumento == 'Cargo' %} {{ p_num_venta }} {% else %} {{ p_num_credito }} {% endif %}" />
      </form>


  </div>
    
  <div class="col-md-3">

    <form action={% url 'pedidos:documentos' %} >
      <input class="btn btn-default " type="submit" value="Continuar..">
    </form>
  </div>
  <div class="col-md-6">
  </div>
</div>
    










<!-- El siguiente div se utiliza como parte del cuadro de dialogo jquery para elminiar clientes -->

<div id="dialog-1" style="display : none;" title="Advertencia !">Los registros seleccionados serán eliminados de manera definitiva de la base de datos, la acción es irreversible, desea continuar ?</div>





{% endblock content %}

pedidos/templates/pedidos/edita_catalogo.html
{% extends 'pedidos/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}



<div class="row">
<!-- <div class="col-md-3"></div>-->
  <div class="col-md-4">

      
  </div>
  <div class="col-md-4">
    <div class="panel panel-success">

        <div class='panel-heading'><h4 align='left'>Edita catalogo<h4></div>
        <div class='panel-body'>
              
            {% if mensaje %}<p><strong> {{mensaje}}</strong></p>{% endif %}

            
            <form action="{% url 'pedidos:edita_catalogo' ProveedorNo Anio Periodo ClaseArticulo %}" method="POST">
                
                    <!--<div class="alert alert-danger" role="alert">
                      {% for error in form.non_field_errors %}
                        {{ error }}
                      {% endfor %}

                     </div>-->
               
               
                    {% csrf_token %}

                    {{ form | crispy }}
                
                    <input  id='btn_crea_proveedor' class="btn btn-default"  type="submit" value="Enviar" />
                

                    
                
             
            </form>

          <!-- 
          <form id="imp_venta_form"  method= 'GET' role="button" {% if  form.doc_tipodedocumento == 'Remision' or  form.doc_tipodedocumento == 'Cargo' %}  action= "{% url 'pedidos:imprime_venta' %}" {% else %} action="{% url 'pedidos:imprime_credito' %}" {% endif %} method="GET"><input id ='idventa' {% if form.doc_tipodedocumento == 'Remision'  %} name ='p_num_venta' {% else %} name ='p_num_credito' {% endif %} class="glyphicon glyphicon-print" type="submit"  value={{ NoDocto }}>
          </form> -->           





        </div><br>
 <div class="col-md-4">
    <br><p align="left">
                            <a href="{% url 'pedidos:lista_catalogos_proveedor' ProveedorNo %}" id="regresar" class="btn btn-success" role="button">Regresar </a>
                          </p>

 </div>     
 
  </div>
        






  <script>
    var is_staff = "{{ is_staff }}";
  </script>  


{% endblock content %}

pedidos/templates/pedidos/elegir_almacen_a_cerrar.html
{% extends 'pedidos/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}

<h5>{{mensaje}}</h5>

<div class="row">
<div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="panel panel-success">
        <div class='panel-heading'><h4 align='left'>Elección del almacén a cerrar<h4></div>
        <div class='panel-body'>
              
                <div class="alert alert-danger" role="alert">
              
                    {{form.non_field_errors}}
                </div>
               
              
            
            {% if error_message %}<p><strong> {{error_message}}</p>{% endif %}
            <form action="{% url 'pedidos:elegir_almacen_a_cerrar' %}" method="POST">
                <div class="form-inline" >
                    {% csrf_token %}

                  
                    <div class="form-group" >
                        <label>Proveedor:            </label>
                        {{form.proveedor  }}
                    </div>
                    <div class="form-group">
                      <label>Almacén:                </label>
                      {{form.almacen }}
                    </div>
                    
                
                    <input  class="btn btn-default"  type="submit" value="Enviar" />
                

                    
                </div>
            </form>

        </div>
       

    </div>  
  <div class="col-md-3"></div>
  </div>
  


{% endblock content %}

pedidos/templates/pedidos/elimina_usuario_derecho.html
 {% extends 'pedidos/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}



<div class="row">
<!-- <div class="col-md-3"></div>-->
  <div class="col-md-4">

      
  </div>
  <div class="col-md-4">
    <div class="panel panel-success">

        <div class='panel-heading'><h4 align='left'><i class="fa fa-user-circle-o"></i>Elimina derecho !<h4></div>
        <div class='panel-body'>
              
            {% if mensaje %}<p><strong> {{mensaje}}</strong></p>{% endif %}
            <div class="alert alert-warning" role="alert">
              <h5> Se procederá a eliminar el derecho seleccionado, si esta seguro de clic en 'Enviar', de otra manera de clic 'Regresar'</h5>
            </div>
            <form action="{% url 'pedidos:eliminar_usuario_derecho' usuariono derechono %}" method="POST">
                
                    <!--<div class="alert alert-danger" role="alert">
                      {% for error in form.non_field_errors %}
                        {{ error }}
                      {% endfor %}

                     </div>-->
               
               
                    {% csrf_token %}


                    {{ form | crispy }}


                
                    <input  id='btn_crea_asociado' class="btn btn-default"  type="submit" value="Enviar" />
                

                    
                
             
            </form>

          <!-- 
          <form id="imp_venta_form"  method= 'GET' role="button" {% if  form.doc_tipodedocumento == 'Remision' or  form.doc_tipodedocumento == 'Cargo' %}  action= "{% url 'pedidos:imprime_venta' %}" {% else %} action="{% url 'pedidos:imprime_credito' %}" {% endif %} method="GET"><input id ='idventa' {% if form.doc_tipodedocumento == 'Remision'  %} name ='p_num_venta' {% else %} name ='p_num_credito' {% endif %} class="glyphicon glyphicon-print" type="submit"  value={{ NoDocto }}>
          </form> -->           





        </div><br>
 <div class="col-md-4">


  <br><p align="left">
                          <a href="{% url 'pedidos:lista_usuario_derechos' usuariono %}" id="regresar" class="btn btn-success" role="button">Regresar </a>
                        </p>


 </div>     
 
  </div>
        






  <script>
    var is_staff = "{{ is_staff }}";
    var ca = "{{ forzarcobroanticipo }}"
    console.log('cobroanticipo')
    console.log(ca)
  </script>  


{% endblock content %}

pedidos/templates/pedidos/error.html
{% extends 'pedidos/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}


<div class="row">
   
  

  <div class="col-md-12">  

    
    {% if error  %} <div class="alert alert-warning" role="warning"> {% else %}<div class="alert alert-success" role="success "> {% endif %}
        <h2>
        Mensaje:</h2>
        <br>

        <h4>{{ error_msg }}</h4> <br>


        <h6>Si Ud. no comprende el mensaje, hagalo llegar a su administrador de sistemas.</h6> 

        
    </div>
    
  </div><br><br>
  <div class="col-md-3">
    
  <div class="col-md-3">
    <!--
    <form action={% url 'pedidos:entrada_sistema' %} >
      <input class="btn btn-default " type="submit" value="Continuar..">
    </form>
  </div>-->
  <div class="col-md-6">
  </div>
</div>
    










<!-- El siguiente div se utiliza como parte del cuadro de dialogo jquery para elminiar clientes -->

<div id="dialog-1" style="display : none;" title="Advertencia !">Los registros seleccionados serán eliminados de manera definitiva de la base de datos, la acción es irreversible, desea continuar ?</div>





{% endblock content %}

pedidos/templates/pedidos/filtro_asociado_catalogos.html
 {% extends 'pedidos/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}

<h5>{{mensaje}}</h5>

<div class="row">
  <div class="col-md-4">
  </div>

  <div class="col-md-4">
    <div class="panel panel-success">
        <div class='panel-heading'><h4 align='left'>Filtra catalogos del socio<h4></div>
        <div class='panel-body'>
            
           
             
            <form id="documentos_form" action="{% url 'pedidos:filtrocatalogosasociado' asociadono %}" method="POST">
              <!--  <div class="alert alert-danger" role="alert">
              
            {{form.non_field_errors}}
            </div>-->

                <div class="form" >
                    {% csrf_token %}
                  
                    <div class="form-group" >
                        {{ form | crispy }}
                       
                    </div>
                    
                    
                    
                    <!--<a class="btn btn-success btn-lg btn-space" id="btn_trae_colocaciones" href="#" role="button"> Traer pedidos...</a>
                    <br> 
                    <input  class="btn btn-default" style="display: none;  type="submit" value="Enviar" /> -->  
               
                  
                    <input  class="btn btn-default" id="btn_documentos" type="submit" value="Enviar" /> -
                

                    
                </div>
            </form>

        </div>
       

    </div>  
   
  </div>
      
    
    
  </div>
  <div class="col-md-4">
    
  </div>
</div>
    










<!-- El siguiente div se utiliza como parte del cuadro de dialogo jquery para elminiar clientes -->

<div id="dialog-1" style="display : none;" title="Advertencia !">Los registros seleccionados serán eliminados de manera definitiva de la base de datos, la acción es irreversible, desea continuar ?</div>





{% endblock content %}

pedidos/templates/pedidos/seleccion_cierre_rpte_cotejo.html
{% extends 'pedidos/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}



<div class="row">
<!-- <div class="col-md-3"></div>-->
  <div class="col-md-8">
    <div class="panel panel-success">
        <div class='panel-heading'><h4 align='left'>Reporte de cotejo, selección del cierre a reportar<h4></div>
        <div class='panel-body'>
              
            {% if mensaje %}<p><strong> {{mensaje}}</strong></p>{% endif %}

          
            <form action="{% url 'pedidos:seleccion_cierre_rpte_cotejo' %}" method="POST">
               <div class="alert alert-danger" role="alert">
              
                    {{form.non_field_errors}}
                </div>
               
                <div class="form-inline" >
                    {% csrf_token %}

                  
                    <div class="form-group" >
                        <label>Proveedor:            </label>
                        {{form.proveedor_rpte_cotejo  }}
                    </div>
                    <div class="form-group">
                      <label>Cierre:                </label>
                      {{form.cierre_rpte_cotejo }}
                    </div>
                    
                
                    <input  id='btn_genera_rpte_cotejo' class="btn btn-default"  type="submit" value="Enviar" />
                

                    
                </div>
             
            </form>

        </div><br>
 
  </div>
        <h4>Lista de Cierres: </h4>
        <div class="table-responsive">
                  
                            <table  class="table table-condensed  thead-default table-hover table-bordered table-inverse ">
                              <tr>
                                <th>id</th>
                                <th> Referencia</th>
                                <th> Fecha Cierre </th>
                                <th> Hora Cierre </th>
                                <th> Fecha llegada </th> 
                                <th> Tot. Articulos</th>
                                <th> Importe </th>
                                <th> Nombre </th>
                                  
                              </tr>

                            
                            </table>
                    </div>
        </div>




  <div class="col-md-4"></div>
  </div>

  <script>
    var is_staff = "{{ is_staff }}";
  </script>  


{% endblock content %}

pedidos/templates/pedidos/vtaneta_socio_xproveedorform.html
{% extends 'pedidos/base.html' %}

{% load crispy_forms_tags %} 

{% block content %}

<h1>{{mensaje}}</h1>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-success">
        <div class='panel-heading'><h4 align='center'>Reporte de ventas netas por socio de un proveedor<h4></div>
        <div class='panel-body'>
    
            {{ mensaje }}
            {% if error_message %}<p><strong> {{error_message}}</p>{% endif %}
            <form action="{% url 'pedidos:vtaneta_socio' %}" method="post">
                <div class="form-group">
                    {% csrf_token %}
                    {{ form | crispy }}<br><br>    
                    
                    <input  class="btn btn-default "  type="submit" value="Enviar" />

                    <a class="btn btn-default" href="{% url 'pedidos:consulta_menu' %}" role="button"> Salir</a>
                </div>
            </form>

        </div>
       

    </div>  
  </div>
  <div class="col-md-4">
    
    
  </div>
  <div class="col-md-4">
    
  </div>
</div>
    



{% endblock content %}