djp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from django.contrib.auth import views


urlpatterns = [
    url(r'^pedidos/',include('pedidos.urls', namespace='pedidos')),
    url(r'^admin/', include(admin.site.urls)),
    
    #url(r'^pedidos/',include('django.contrib.auth.urls', namespace='pedidos')),
    url(r'^reportes/',include('reportes.urls', namespace='reportes')),
    ]
'''url(r'^accounts/', include('registration.backends.simple.urls')),'''
    


pedidos/urls.py
	url(r'^reset/password_done/$',password_reset_done,
		{'template_name':'pedidos/password_reset_done.html','current_app':'pedidos'},
		name ='password_reset_done'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		password_reset_confirm,
		{'template_name':'pedidos/password_reset_confirm.html',
		'current_app':'pedidos','post_reset_redirect' : 'pedidos:password_reset_complete'},
		name ='password_reset_confirm'),
	url(r'^reset/password_complete/$',password_reset_complete,
		{'template_name':'pedidos/password_reset_complete.html','current_app':'pedidos'},
		name ='password_reset_complete'),
	url(r'^empleados/$',views.empleados,name='empleados'),
	url(r'^entrada_sistema/$',views.entrada_sistema,name='entrada_sistema'),
	url(r'^consulta_menu/$',views.consulta_menu,name='consulta_menu'),
	url(r'^calzadollego_gral/$',views.calzadollego_gral,name='calzadollego_gral'),
	url(r'^con_pedidos_por_socio_status/$',views.con_pedidos_por_socio_status,name='con_pedidos_por_socio_status'),
	url(r'^con_confirmaciones/$',views.con_confirmaciones,name='con_confirmaciones'),
	url(r'^existe_socio/$',views.existe_socio,name='existe_socio'),
	url(r'^picklist_socio/$',views.picklist_socio,name='picklist_socio'),
	url(r'^calzadoquellego_detalle/$',views.calzadoquellego_detalle,name='calzadoquellego_detalle'),
	url(r'^consultacolocaciones/$',views.consultacolocaciones,name='consultacolocaciones'),
	url(r'^consultaventas/$',views.consultaventas,name='consultaventas'),
	url(r'^consultacomisiones/$',views.consultacomisiones,name='consultacomisiones'),
	url(r'^buscapedidosposfecha/$',views.buscapedidosposfecha,name='buscapedidosposfecha'),
	url(r'^pedidosgeneral/$',views.pedidosgeneral,name='pedidosgeneral'),
	# url(r'^pedidosgeneraldetalle/(?P<pedido>[0-9]{1,8})/(?P<productono>[\w\-]+)/(?P<catalogo>[\w\-]+)/(?P<nolinea>[0-9]{1,8})/$',views.pedidosgeneraldetalle,name='pedidosgeneraldetalle'),
	url(r'^pedidosgeneraldetalle/(?P<pedido>[0-9]{1,8})/(?P<productono>.*)/(?P<catalogo>.*)/(?P<nolinea>[0-9]{1,8})/$',views.pedidosgeneraldetalle,name='pedidosgeneraldetalle'),
	#url(r'^cancelarpedidoadvertencia/(?P<pedido>[0-9]{1,8})/(?P<productono>[\w\-]+)/(?P<catalogo>[\w \-]+)/(?P<nolinea>[0-9]{1,8})/$',views.cancelarpedidoadvertencia,name='cancelarpedidoadvertencia'),
	url(r'^cancelarpedidoadvertencia/(?P<pedido>[0-9]{1,8})/(?P<productono>.*)/(?P<catalogo>.*)/(?P<nolinea>[0-9]{1,8})/$',views.cancelarpedidoadvertencia,name='cancelarpedidoadvertencia'),
	#url(r'^ingresa_socio/$',views.ingresa_socio,name='ingresa_socio'),
	url(r'^ingresa_socio/(?P<tipo>[D,P,V]{1})/$',views.ingresa_socio,name='ingresa_socio'),

	url(r'^imprime_ticket/$',views.imprime_ticket,name='imprime_ticket'),
	#url(r'^i_d/$',imprime_documento.i_d,name='i_d'),
	url(r'^colocaciones/$',views.colocaciones,name='colocaciones'),
	url(r'^combo_almacenes/$',views.combo_almacenes,name='combo_almacenes'),
	url(r'^muestra_colocaciones/$',views.muestra_colocaciones,name='muestra_colocaciones'),
	url(r'^procesar_colocaciones/$',views.procesar_colocaciones,name='procesar_colocaciones'),
	url(r'^elegir_almacen_a_cerrar/$',views.elegir_almacen_a_cerrar,name='elegir_almacen_a_cerrar'),
	url(r'^procesar_cierre_pedido/$',views.procesar_cierre_pedido,name='procesar_cierre_pedido'),
	url(r'^pruebaImprime/$',views.pruebaImprime,name='pruebaImprime'),
	url(r'^seleccion_cierre_rpte_cotejo/$',views.seleccion_cierre_rpte_cotejo,name='seleccion_cierre_rpte_cotejo'),
	url(r'^combo_proveedor_rpte_cotejo/$',views.combo_proveedor_rpte_cotejo,name='combo_proveedor_rpte_cotejo'),
	url(r'^seleccion_cierre_recepcion/$',views.seleccion_cierre_recepcion,name='seleccion_cierre_recepcion'),
	url(r'^procesar_recepcion/$',views.procesar_recepcion,name='procesar_recepcion'),
	url(r'^documentos/$',views.documentos,name='documentos'),
	url(r'^muestra_documentos/$',views.muestra_documentos,name='muestra_documentos'),
	url(r'^detalle_documento/(?P<NoDocto>[0-9]{1,8})/$',views.detalle_documento,name='detalle_documento'),
	url(r'^crea_documento/$',views.crea_documento,name='crea_documento'),
	url(r'^consulta_menu/$',views.consulta_menu,name='consulta_menu'),
	url(r'^nueva_venta/$',views.nueva_venta,name='nueva_venta'),
	url(r'^calcula_descuento/$',views.calcula_descuento,name='calcula_descuento'),
	url(r'^procesar_venta/$',views.procesar_venta,name='procesar_venta'),
	url(r'^picklist_estilopagina/$',views.picklist_estilopagina,name='picklist_estilopagina'),
	url(r'^consultadsctos/$',views.consultadsctos,name='consultadsctos'),
	url(r'^consultavtasxproveedor/$',views.consultavtasxproveedor,name='consultavtasxproveedor'),
	url(r'^valida_usr/$',views.valida_usr,name='valida_usr'),
	url(r'^detallevtaxproveedor/(?P<idproveedor>[0-9]{1,8})/(?P<fechainicial>[\w\-]+)/(?P<fechafinal>[\w\-]+)/(?P<sucursalinicial>[0-9]{1,8})/(?P<sucursalfinal>[0-9]{1,8})/$',views.detallevtaxproveedor,name='detallevtaxproveedor'),
	url(r'^detallevtaxsocio/(?P<idproveedor>[0-9]{1,8})/(?P<fechainicial>[\w\-]+)/(?P<fechafinal>[\w\-]+)/(?P<sucursalinicial>[0-9]{1,8})/(?P<sucursalfinal>[0-9]{1,8})/(?P<asociadono>[0-9]{1,8})/$',views.detallevtaxsocio,name='detallevtaxsocio'),
	url(r'^trae_nombre_socio/$',views.trae_nombre_socio,name='trae_nombre_socio'),
	url(r'^modifica_cierre/(?P<id>[0-9]{1,8})/$',views.modifica_cierre,name='modifica_cierre'),
	url(r'^imprime_venta/$',views.imprime_venta,name='imprime_venta'),
	url(r'^imprime_documento/$',views.imprime_documento,name='imprime_documento'),
	url(r'^cancelar_pedido/$',views.cancelar_pedido,name='cancelar_pedido'),
	url(r'^devolucion_socio/$',views.devolucion_socio,name='devolucion_socio'),
	url(r'^procesar_devolucion_socio/$',views.procesar_devolucion_socio,name='procesar_devolucion_socio'),
	url(r'^imprime_credito/$',views.imprime_credito,name='imprime_credito'),
	url(r'^calcula_bono/$',views.calcula_bono,name='calcula_bono'),
	url(r'^detallebonosocio/(?P<idsocio>[0-9]{1,8})/(?P<fechainicial>[\w\-]+)/(?P<fechafinal>[\w\-]+)/$',views.detallebonosocio,name='detallebonosocio'),
	url(r'^vtaneta_socio/$',views.vtaneta_socio,name='vtaneta_socio'),
	url(r'^vtaneta_socio_gral/$',views.vtaneta_socio_gral,name='vtaneta_socio_gral'),
	url(r'^vtaneta_socio_proveedor_gral/(?P<fechainicial>[\w\-]+)/(?P<fechafinal>[\w\-]+)/(?P<asociadoini>[0-9]{1,8})/(?P<asociadofin>[0-9]{1,8})/$',views.vtaneta_socio_proveedor_gral,name='vtaneta_socio_proveedor_gral'),
	url(r'^cancelardocumentoadvertencia/(?P<NoDocto>[0-9]{1,8})/$',views.cancelardocumentoadvertencia,name='cancelardocumentoadvertencia'),	
	url(r'^rptedecreditos/$',views.rptedecreditos,name='rptedecreditos'),
	url(r'^recepcion_dev_prov/$',views.recepcion_dev_prov,name='recepcion_dev_prov'),
	url(r'^procesar_recepcion_devolucion_proveedor/$',views.procesar_recepcion_devolucion_proveedor,name='procesar_recepcion_devolucion_proveedor'),
	url(r'^devolucion_a_proveedor/$',views.devolucion_a_proveedor,name='devolucion_a_proveedor'),
	url(r'^procesar_devolucion_proveedor/$',views.procesar_devolucion_proveedor,name='procesar_devolucion_proveedor'),
	url(r'^filtro_dev_prov/$',views.filtro_dev_prov,name='filtro_dev_prov'),
	url(r'^imprime_hoja_devolucion/$',views.imprime_hoja_devolucion,name='imprime_hoja_devolucion'),
	url(r'^edita_devprov/(?P<id_prov>[0-9]{1,8})/$',views.edita_devprov,name='edita_devprov'),
	url(r'^proveedores/$',views.proveedores,name='proveedores'),
	url(r'^edita_proveedor/(?P<proveedorno>[0-9]{1,8})/$',views.edita_proveedor,name='edita_proveedor'),
	url(r'^crea_proveedor/$',views.crea_proveedor,name='crea_proveedor'),
	url(r'^lista_catalogos_proveedor/(?P<proveedorno>[0-9]{1,8})/$',views.lista_catalogos_proveedor,name='lista_catalogos_proveedor'),
	url(r'^edita_catalogo/(?P<p_ProveedorNo>[0-9]{1,8})/(?P<p_Anio>[0-9]{1,8})/(?P<p_Periodo>[0-9]{1,8})/(?P<p_ClaseArticulo>.*)/$',views.edita_catalogo,name='edita_catalogo'),
	url(r'^crea_catalogo/(?P<id_proveedor>[0-9]{1,8})/$',views.crea_catalogo,name='crea_catalogo'),
	url(r'^lista_devoluciones_recepcionadas/$',views.lista_devoluciones_recepcionadas,name='lista_devoluciones_recepcionadas'),
	url(r'^rpte_ventas/$',views.rpte_ventas,name='rpte_ventas'),
	url(r'^rpteStatusPedidosPorSocio/$',views.rpteStatusPedidosPorSocio,name='rpteStatusPedidosPorSocio'),
	url(r'^vtasporusuario/$',views.vtasporusuario,name='vtasporusuario'),
	url(r'^busca_estilo/$',views.busca_estilo,name='busca_estilo'),
	url(r'^piezas_no_solicitadas/$',views.piezas_no_solicitadas,name='piezas_no_solicitadas'),
	url(r'^rpte_piezas_no_solicitadas/$',views.rpte_piezas_no_solicitadas,name='rpte_piezas_no_solicitadas'),
	url(r'^filtrocatalogosasociado/(?P<asociadono>[0-9]{1,8})/$',views.filtrocatalogosasociado,name='filtrocatalogosasociado'),
	url(r'^filtroproveedor_almacen/$',views.filtroproveedor_almacen,name='filtroproveedor_almacen'),
	url(r'^crea_almacen/(?P<proveedorno>[0-9]{1,8})/$',views.crea_almacen,name='crea_almacen'),
	url(r'^edita_almacen/(?P<proveedorno>[0-9]{1,8})/(?P<almacenno>[0-9]{1,8})/$',views.edita_almacen,name='edita_almacen'),
	url(r'^rpte_remisiones_especiales/$',views.rpte_remisiones_especiales,name='rpte_remisiones_especiales'),
	url(r'^lista_usuarios/$',views.lista_usuarios,name='lista_usuarios'),
	url(r'^edita_usuario/(?P<usuariono>[0-9]{1,8})/$',views.edita_usuario,name='edita_usuario'),
	url(r'^crea_usuario/$',views.crea_usuario,name='crea_usuario'),
	url(r'^lista_usuario_derechos/(?P<usuariono>[0-9]{1,8})/$',views.lista_usuario_derechos,name='lista_usuario_derechos'),
	url(r'^agregar_usuario_derecho/(?P<usuariono>[0-9]{1,8})/$',views.agregar_usuario_derecho,name='agregar_usuario_derecho'),
	url(r'^eliminar_usuario_derecho/(?P<usuariono>[0-9]{1,8})/(?P<derechono>[0-9]{1,8})/$',views.eliminar_usuario_derecho,name='eliminar_usuario_derecho'),
	url(r'^lista_usuarios_web/$',views.lista_usuarios_web,name='lista_usuarios_web'),

reportes/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
	url(r'^$',views.listaclientes,name='listaclientes'),
    url(r'^creacliente/$',views.creacliente, name='creacliente'),
    url(r'^modificacliente/(?P<id_cliente>[0-9]+)/$',views.modificacliente, name='modificacliente'),
    url(r'^reportes/(?P<id_cliente>[0-9]+)/$',views.reportes_por_cliente, name='reportes_por_cliente'),
    url(r'^$',views.clienteactualizado,name='clienteactualizado'),
    url(r'^eliminaclientes/$',views.eliminaclientes,name='eliminaclientes'),
    url(r'^commitdelclientes/$',views.commitdelclientes,name='commitdelclientes'),
    url(r'^filtraclientes/$',views.filtraclientes, name='filtraclientes'),
    ]

reportes/models.py
from django.db import models

class Cliente(models.Model):
	nombre =models.CharField(verbose_name='Nombre', max_length=100)
	domicilio = models.CharField(verbose_name='Domicilio',max_length=200)
	email = models.EmailField(verbose_name='email',max_length=200)

	def __str__(self):
		return self.nombre

class Reporte(models.Model):
	descripcion = models.CharField(max_length=5000)
	Solucion = models.CharField(max_length=5000)
	fecha_mod = models.DateField()
	id_cliente =models.ForeignKey(Cliente)

	def __str__(self):
		return self.descripcion

		# Create your models here.

reportes/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render,get_object_or_404,redirect,render_to_response
from django.db.models import Q
from django.http import HttpResponse,HttpResponseRedirect
from django_tables2 import RequestConfig
from .models import Cliente,Reporte
from django.template import RequestContext,loader
from django.core.urlresolvers import reverse
from .forms import ClienteForm,FiltraclienteForm
from .tables import ClienteTable, ClienteTableSeleccionados


''' FUNCION PARA LISTAR CLIENTES '''


'''def listaclientes(request):
	cl = Cliente.objects.all()
	context = {'cl':cl,}
	return render(request,'reportes/listaclientes.html',context )'''

def listaclientes(request):
	cl = ClienteTable(Cliente.objects.all())
	mensaje = 'Asi esta la cosa !'
	RequestConfig(request, paginate={"per_page":10}).configure(cl)
	#RequestConfig(request).configure(cl)
	context = {'cl':cl,'mensaje':mensaje,}
	return render(request,'reportes/listaclientes.html',context)

def filtraclientes(request):
	if request.method == 'POST':
		form = FiltraclienteForm(request.POST)
		print form.is_valid()
		if form.is_valid():
			''' limpia datos '''
			buscar_por = form.cleaned_data['buscar_por']
			id_cliente = form.cleaned_data['id_cliente']
			token_to_search = form.cleaned_data['token_to_search']
			
			
			if buscar_por == '1':
				queryset = Cliente.objects.filter(pk=id_cliente)
				cl = ClienteTable(queryset)
			else :
				queryset = Cliente.objects.filter(Q(nombre__icontains=token_to_search) | Q(domicilio__icontains = token_to_search))
				cl = ClienteTable(queryset)
			
			if not queryset.exists():
				mensaje ='No se encontraron registros en la base de datos...'
			else:
				mensaje ="Resultados obtenidos:"

			RequestConfig(request,paginate={"per_page":10}).configure(cl)
			context = {'cl':cl,'mensaje':mensaje}
			return render(request,'reportes/listaclientes.html',context)
		else:
			form = FiltraclienteForm()
	form = FiltraclienteForm()
	return render(request,'reportes/filtraclientes.html',{'form':form,})


''' FUNCION PARA CREAR CLIENTES '''

def creacliente(request):
	mensaje = 'Ingrese datos del cliente'
	if request.method =='POST':
		form = ClienteForm(request.POST)
		if form.is_valid():
			form.save()
			mensaje = "Cliente agregado correctamente.! "
			return HttpResponseRedirect(reverse('reportes:listaclientes',args=()),{'mensaje':mensaje,})
	else:
		form = ClienteForm()
	return render(request,'reportes/creacliente.html',{'form':form,})



''' FUNCION PARA MODIFICAR CLIENTES'''


def modificacliente(request,id_cliente):
	import pdb
	pdb.set_trace()
	cl = get_object_or_404(Cliente,pk=id_cliente)
	print id_cliente
	mensaje ='Cliente aun no modificado !'
	
	if request.method =='POST':
		form = ClienteForm(request.POST)
		if form.is_valid():
			nombre = form.cleaned_data['nombre']
			domicilio = form.cleaned_data['domicilio']
			email = form.cleaned_data['email']
			cl.nombre = nombre.upper()
			cl.domicilio = domicilio.upper()
			cl.email = email
			cl.save()
			mensaje = "Cliente modificado correctamente.! "
			return HttpResponseRedirect(reverse('reportes:listaclientes',args=()))
	else:
		mensaje ='entro aqui'
		form = ClienteForm(initial={'id':cl.id, 'nombre':cl.nombre,'domicilio':cl.domicilio,'email':cl.email,})
		print form
		print mensaje
	return render(request,'reportes/modificacliente.html',{'form':form,'mensaje':mensaje,'id_cliente':id_cliente})


def eliminaclientes(request):
	cl = ''
	mensaje = ''
	if request.method == 'POST':
		mensaje = "Advertencia !  Los siguientes registros han sido seleccionados para ser eliminados:"
		pks = request.POST.getlist("sel")
		cl = ClienteTableSeleccionados(Cliente.objects.filter(pk__in= pks))
		#cl = Cliente.objects.filter(nombre__in = pks)
		RequestConfig(request,paginate ={'per_page':25}).configure(cl)
	return render(request,'reportes/eliminaclientes.html',{'cl':cl,'mensaje':mensaje,'pks':pks,})	

def commitdelclientes(request):
	pks = request.POST.getlist("sel")
	print pks
	#cl= ClienteTableSeleccionados(Cliente.objects.filter(pk__in= pks))
	if request.method == 'POST':
		mensaje = " Clientes eliminados con éxito !"
		for r in pks:
			Cliente.objects.filter(pk=r).delete()
	cl = ClienteTable(Cliente.objects.all())
	return render(request,'reportes/listaclientes.html',{'pks':pks,'cl':cl,})

	

''' FUNCION PARA LISTAR REPORTES DE UN CLIENTE '''


def reportes_por_cliente(request,id_cliente):
	cl = Cliente.objects.get(pk=id_cliente)
	re = Reporte.objects.filter(id_cliente=cl.id)
	template = loader.get_template('reportes/reportes_por_cliente.html')
	context = RequestContext(request,{'re':re,'cl':cl,})
	return HttpResponse(template.render(context))

def clienteactualizado(request):
	mensaje = "Cliente actualizado con exito !"
	return render(request,'reportes/clienteactualizado.html',{'mensaje':mensaje,})

def muestracliente(request,id_cliente):

	cl = Cliente.objects.get(pk=id_cliente)
	response = "Estas en muestracliente viendo el cliente %s, con numero %s" 
	return HttpResponse(response %(cl,id_cliente))

def reportes_por_cliente_alterno(request,id_cliente):

	ReporteFormSet = inlineformset_factory(Cliente, Reporte, fields=('descripcion',))
	cliente = Cliente.objects.get(pk=id_cliente)
	formset = ReporteFormSet(instance=cliente)
	return render(request,'reportes/reportes_por_cliente_alterno.html',{'cl':cliente,'formset':formset,})






reportes/templates/reportes/cliente.html
<h1>Editando </h1>


{% if error_message %}<p><strong> {{error_message}}</p>{% endif %}
<form action="{% url 'reportes:creacliente' 1 %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Enviar.." />
</form>
<!--
<label for="nombre">Nombre: </label>
<input id="nombre" type='edit' name = "nombre:" value="{{cte.nombre}}"/><br>
<label for="domicilio">Domicilio: </label>
<input id="domicilio" type='edit' name = "domicilio:"  value="{{cte.domicilio}}"/><br>
<label for="email">Buzon Electronico:</label>
<input id ="email" type='email' name = "email:" value="{{cte.email}}"/><br><br>
<input type='submit' value='Enviar' />
</form>
-->

reportes/templates/reportes/clienteactualizado.html
<h1> {{ mensaje }} </h1>

reportes/templates/reportes/copiadeListaclientes.html
{% extends 'reportes/base.html' %}



{% block content %}

<h3>CLIENTES ACTIVOS</h3><br>



{% load render_table from django_tables2 %}

{% render_table cl %}


<h5> {{mensaje}} </h5><br><br>
<a class="btn btn-default" href="{% url 'reportes:creacliente' %}" role="button">Agregar nuevo</a>

{% endblock content %}

reportes/templates/reportes/copiadeListaclientes1.html
{% extends 'reportes/base.html' %}



{% block content %}

<h3>CLIENTES ACTIVOS</h3><br>



{% load render_table from django_tables2 %}

{% render_table cl %}


<h5> {{mensaje}} </h5><br><br>
<a class="btn btn-default" href="{% url 'reportes:creacliente' %}" role="button">Agregar nuevo</a>

{% endblock content %}

reportes/templates/reportes/creacliente.html
{% extends 'reportes/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Creando Cliente... </h3>
{{ mensaje }}
{% if error_message %}<p><strong> {{error_message}}</p>{% endif %}
<form action="{% url 'reportes:creacliente' %}" method="post">
	<div class="form-group">
		{% csrf_token %}
		{{ form|crispy}}
		<input type="submit" value="Enviar.." />
	</div>
</form>
{% endblock %}
<!--
<label for="nombre">Nombre: </label>
<input id="nombre" type='edit' name = "nombre:" value="{{cte.nombre}}"/><br>
<label for="domicilio">Domicilio: </label>
<input id="domicilio" type='edit' name = "domicilio:"  value="{{cte.domicilio}}"/><br>
<label for="email">Buzon Electronico:</label>
<input id ="email" type='email' name = "email:" value="{{cte.email}}"/><br><br>
<input type='submit' value='Enviar' />
</form>
-->

reportes/templates/reportes/eliminaclientes.html
{% extends 'reportes/base.html' %}


{% block content %}
<div class="alert alert-danger" role="alert">
	<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
	<span class="sr-only">Error:</span>
	{{ mensaje }}
</div>

<form action="{% url 'reportes:commitdelclientes' %}" method="post">
	{% csrf_token %}
	<div align = "Center">{% load render_table from django_tables2 %}</div>
	<div align = "Center">{% render_table cl %}</div>
	
    <div align = "Right"><input type="submit" class="btn btn-default" value="Confirmar"/></div>
</form>
<!--<a class="btn btn-default" href="{% url 'reportes:listaclientes' %}" role="button">Regresar</a> -->
{% endblock content %}

reportes/templates/reportes/filtraclientes.html
{% extends 'reportes/base.html' %}
{% load crispy_forms_tags %} 

{% block content %}
<h2>Búsqueda de clientes... </h2>
{{ mensaje }}
{% if error_message %}<p><strong> {{error_message}}</p>{% endif %}
<form action="{% url 'reportes:filtraclientes' %}" method="post">
	<div class="form-group">
		{% csrf_token %}
		{{ form|crispy}}
		<input type="submit" value="Enviar.." />
	</div>
</form>
{% endblock %}

reportes/templates/reportes/listaclientes.html
{% extends 'reportes/base.html' %}

{% block content %}

<h1>{{mensaje}}</h1>

<div class="row">
  <div class="col-md-3"><h3>Clientes activos</h3></div>
  <div class="col-md-3"></div>
  <div class="col-md-3"></div>
  <div class="col-md-3" align = "Right"><h3><a class="btn btn-info btn-normal" href="{% url 'reportes:creacliente' %}" role="button">Nuevo cliente </a></h3></div>
</div>

<form  action="{% url 'reportes:commitdelclientes' %}" method="post">
	{% csrf_token %}
	<div align = "Center">{% load render_table from django_tables2 %}</div>
	<div align ="Center">{% render_table cl %}</div>
	<div align ="Right"><input id="submcltes" type="submit" style="display: none;" class="btn btn-default" value="Eliminar(no se muestra)"/></div>
</form>
<br>

<button  id="eliminaclientes" class="btn btn-danger btn-normal">Eliminar</button>





<!-- El siguiente div se utiliza como parte del cuadro de dialogo jquery para elminiar clientes -->

<div id="dialog-1" style="display : none;" title="Advertencia !">Los registros seleccionados serán eliminados de manera definitiva de la base de datos, la acción es irreversible, desea continuar ?</div>





{% endblock content %}

reportes/templates/reportes/modificacliente.html
{% extends 'reportes/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	
	<form action="{% url 'reportes:modificacliente' id_cliente %}" method="post"> 
	{% csrf_token %}
	<tr>
		<th>
			<label for="id_nombre">Nombre:</label>
		</th><br>
		<td id='name'>
			{{form.nombre}}
		</td>
	</tr><br><br>
	<tr>
		<th>
			<label for="id_domicilio">Domicilio:</label>
		</th><br>
		<td maxlength="100">
			{{ form.domicilio}}
		</td><br><br>
	</tr>
	<tr><br>
		<th>
			<label for="id_email">Email:</label>
		</th>
		<td><br>
			{{ form.email }}
		</td>
	</tr><br><br>
	<input type='submit' value='Enviar' />
	</form>
	

















<!--
<h1>Editando </h1>
{{ mensaje }}

{% if error_message %}<p><strong> {{error_message}}</p>{% endif %}
<form action="{% url 'reportes:modificacliente' id_cliente %}" method="post">
{% csrf_token %}
{{ form | crispy }}
<input type="submit" value="Enviar.." />
</form>
-->
{% endblock %}





reportes/templates/reportes/pruebadialog2.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Demo</title>
</head>
<body>
    <a href="http://jquery.com/">jQuery</a>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>"></script>
    <script type ="text/javascript">
 
    // Your code goes here.
    $( document ).ready(function() {
 
    $( "p" ).click(function( event ) {
 
        alert( "As you can see, the link no longer took you to jquery.com" );
 
        //event.preventDefault();
 
    });
 
});
 
    </script>

    <p>prueba</p>
</body>
</html>

reportes/templates/reportes/reportes_por_cliente.html
<h1>REPORTES DE {{cl.nombre}}</h1><br>
<ul>
<h5><td>DESCRIPCION</td></H5>
{% for x in re %}
	<li>{{x.id}} {{x.descripcion}}</li>
{% endfor %}
</ul>

reportes/templates/reportes/reportes_por_cliente_alterno.html
<h1>REPORTES DE {{cl.nombre}}</h1><br>
<ul>
<h5><td>DESCRIPCION</td></H5>
{% for x in re %}
	<li>{{x.id}} {{x.descripcion}}</li>
{% endfor %}
</ul>